version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
      - 443:443
    networks:
      - network
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - django_container
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - static_volume:/home/app/django_3_22/staticfiles    

  django_container:
    build:
      context: .
    image: django_course:v1.0.0
    networks:
      - network
    volumes:
      - static_volume:/home/app/django_3_22/staticfiles
      - sqlite_volume:/home/app/django_3_22/db 
    environment:
      - DJANGO_SECRET_KEY=super-secret-key
      - DATABASE_NAME=/home/app/django_3_22/db/db.sqlite3
      - DATABASE_PATH=/home/app/django_3_22/db

networks:
  network:

volumes:
  static_volume:
  sqlite_volume:

configs:
  nginx_conf:
    external: true  
